export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const LANGUAGES_CHANGE = 'LANGUAGES_CHANGE'
export const LOGGING_CHANGE = 'LOGGING_CHANGE'
export const API_CHANGE = 'API_CHANGE'
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';