export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const LANGUAGES_CHANGE = 'LANGUAGES_CHANGE'
export const LOGGING_CHANGE = 'LOGGING_CHANGE'
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';